BaseURL = "https://taufiq33.github.io"
languageCode = "id-id"
defaultContentLanguage = "id"
author = "Taufiq Hidayat"
title = "KalilikaBlog"
theme = "hugo-vitae"
paginate = 5
enableRobotsTXT = true

copyright = "© Copyright 2022 | [Taufiq Hidayat](https://github.com/taufiq33)"

pygmentsstyle = "colorful"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

googleAnalytics = ""

[taxonomies]
	tag = "tags"
	category = "categories"
	series = "series"

[params]
	# Enable dark mode as default
	#darkmode = true

	# Use homepage.md instead of a list of posts
	homepage = false

	# Add meta keywords in head part (Site Keywords or Tags of Page)
	keywords = ["hugo","vitae","theme","static"]

	# Add meta description in head part
	description = "Blog untuk menuliskan apa yang saya ketahui."

	# Add pagetitle to homepage <title> tag
	pagetitle = ""

	# Add a subtitle to your website
	subtitle = "Blog untuk menuliskan apa yang saya ketahui."

	# Add math typesetting with KaTeX (Global with this Param)
	math = true

	# Optional 80x80 avatar image.
	avatar = "/kalilika.png"

	# Optional favicons for website
	favicon = true

	# Add list of sections that should show up on the homepage
	mainSections = ["post"]

	# Add list of Sections/Types that should no be considered by RSS
	#nofeedSections = ["post"]

	# Deactivate Taxonomies for specific page types
	#disableTaxoTypes = [""]

	# Custom CSS applied to default styles. (Path could be "static/css/")
	#customcss = "css/custom.css"

	# Show reading time on a post
	readingTime = true

	# Show word count on a post
	wordCount = true

	# Show author on a post (groups with readingTime and wordCount)
	hideAuthor = false

# Custom JavaScript
[params.customjs]
# enable Javascript by setting to true
enabled = false

# add a filepath (could be "static/js/")
#src = "js/main.js"

# specifies which referrer information to send when fetching the script
#referrerpolicy = "no-referrer"

# specifies that the script should not be executed in browsers supporting ES2015 modules
#nomodule = false

# Allows a browser to check for integrity to ensure the code hasn't been manipulated
#integrity= ""

# execute the script when page has finished parsing (external only)
#defer = true

# sets the mode of the request to an http cors request
#crossorigin=true

# executes the script asynchronously (external only)
#async = true

# Comments
[params.comments]
# Enable Comments with "true"
enabled = true

# Comment provider:
#   disqus (https://disqus.com)
#   commento (https://commento.io)
#engine = "disqus"

# Content types to disable comments on.
#disableOnTypes = ["page"]

[params.comments.disqus]
#shortname = "" # Paste the shortname from your Disqus dashboard.

[params.comments.commento]
#host = "" # Paste the domain of you commento.io system

# Navigation
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All Posts"
url = "/post"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

#[[menu.main]]
#name = "Tags"
#url = "/tags"
#weight = 4

#[[menu.main]]
#name = "Categories"
#url = "/categories"
#weight = 5

# Social Menu
[[params.social]]
name = "Github"
icon = "fab fa-github"
url = "https://github.com/taufiq33"

#[[params.social]]
#name = "Email"
#icon = "fas fa-envelope"
#cmd = "mailto:taufiqhidayat1908@gmail.com"

[[params.social]]
name = "RSS"
icon = "fas fa-rss"
url = "/index.xml"
